spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tutor-web
    username: postgres
    password: password
  view:
    prefix: /WEB-INF/jsp/
    suffix: .jsp
  mvc:
    favicon:
      enabled: false